config/routes.rb
Rails.application.routes.draw do
  get 'join_game_requests/send_request'

  get 'join_game_requests/answer_request'

  root 'static_pages#home'
  get 'milestones' => 'static_pages#milestones'
  resources :users do
    resources :statements
    
  end 
  resources :monsters
  get 'all_users' => 'users#index'
  get 'signup' => 'users#new'
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :characters
  get 'character_creator' => 'characters#new'
  put 'action' => 'characters#character_action'

  resources :games do
    resources :statements
    resources :encounters 
  end

  resources :combat_actions

  get 'play/:id' => 'games#play'
  get 'game_stuff' => 'static_pages#games'
  get 'choose_character' => 'games#pick_character'
  put 'add_to_game' => 'games#add_character_to_game'
  get 'games/:id/characters' => 'games#game_characters'
  get 'your_games' => 'games#games_you_play' 
  get 'games/:id/add_monsters' => 'games#add_monsters_to_games'

  post 'statements/do_action' => 'statements#do_action'
  post 'statements/make_saves' => 'statements#make_saves'
  post 'games/add_monsters' => 'games#save_monsters_to_games'
  post 'monsters/add_abilities' => 'monsters#save_abilities_to_monsters'
  post 'join_game_requests/send' => 'join_game_requests#send_request'
  post 'join_game_requests/answer' => 'join_game_requests#answer_request'
  

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :characters
	has_many :statements
	has_many :combat_actions

	has_many :monster_ownerships
	has_many :monsters, :through => :monster_ownerships	

	has_many :item_ownerships
	has_many :weapons, :through => :item_ownerships
	has_many :armors, :through	=> :item_ownerships	

	validates :email, presence: true, length: { maximum: 255 }
	validates :password, length: { minimum: 6 }
	#validates :username, presence: true
	has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

#before_action :logged_in_user, only: [:edit, :destroy, :index, :show]
before_action :correct_user, only: [:show]

########################### standard actions 
	
	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
		@characters = @user.characters
		@monsters = @user.monsters
		@games = Game.where(gamemaster_id: @user.id)
		@combat_actions = @user.combat_actions					
	end

	def new
		@user = User.new		
	end

	def create
		@user = User.new(user_params)
		if @user.save
			log_in(@user)
			redirect_to @user
		else
			flash[:danger] = "something went wrong"
			render 'new'
		end
	end



	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
      		flash[:success] = "Profile updated"	
      		redirect_to @user		
		else
      		flash[:error] = "failed"	
      		redirect_to @user
		end
	end

	def destroy
		
	end
#####################
	def user_params # selected attributes of user object passed as a hash
		params.require(:user).permit(:username, :email, :password, :password_confirmation)
	end

	def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "please log in"
        redirect_to login_url
      end 
	end

	def correct_user
		@user = User.find(params[:id])		
    	
		if current_user != @user
			redirect_to(root_url)
			flash[:danger] = "you can only view/edit your own profile"				
		end
	end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>

<%= f.label :usename %>
<%= f.text_field :username, class: 'form-control' %>

<%= f.label :email %>
<%= f.email_field :email, class: 'form-control' %>

<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>

<%= f.submit "update" %>

<% end %>

app/views/users/new.html.erb
<h1> sign up </h1>

    <%= form_for(@user) do |f| %>
        <%= f.label :usename %>
        <%= f.text_field :username, class: 'form-control' %>

     	<%= f.label :email %>
    	<%= f.email_field :email, class: 'form-control' %>
    	
    	<%= f.label :password %>
    	<%= f.password_field :password, class: 'form-control' %>

    	<%= f.label :password_confirmation, "Confirmation" %>
    	<%= f.password_field :password_confirmation, class: 'form-control' %>    	    

    	<%= f.submit "Create my account", class: "btn btn-primary" %>

    <% end %>    	

app/views/users/show.html.erb
<p><%= link_to "edit profile", edit_user_path(current_user) %> </p> 
<h1> 
	<p> username: <%= @user.username %> </p>
	<p> email: <%= @user.email %> </p>
	
</h1>

<div id="user-container">
    <ul id="users-things">
  
    <li id="characters-menu">
    characters
    <ul id="sub-things">
      <li id="new"><%= link_to "make new character", "/characters/new" %></li>     
      <% @characters.each do |character| %>
        <li>
          <%= link_to character.race, character %> 
          <%= link_to character.character_class, character %>
        </li>
      <% end %>
    </ul>
  </li>

  <li id="games-menu">
    games
    <ul id="sub-things">
      <li id="new"><%= link_to "start a new game", "/games/new" %></li>     
      <% @games.each do |game| %>
        <li>
          <%= link_to game.name, game %> 
        </li>
      <% end %>
    </ul>
  </li>

  <li id="monsters-menu">
    monsters
    <ul id="sub-things">
      <li id="new"><%= link_to "make a new monster", "/monsters/new" %></li>
      <% @monsters.each do |monster| %>
        <li>
          <%= link_to monster.name, monster %> 
        </li>
      <% end %>
    </ul>
  </li>
    
  <li id="combat-actions-menu">
    combat actions
    <ul id="sub-things">
      <li id="new"><%= link_to "create a new combat action", "/combat_actions/new" %></li>     
      <% @combat_actions.each do |action| %>
        <li>
          <%= link_to action.name, action %> 
        </li>
      <% end %>
    </ul>
  </li>

</ul>
</div>