config/routes.rb
Rails.application.routes.draw do
  get 'join_game_requests/send_request'

  get 'join_game_requests/answer_request'

  root 'static_pages#home'
  get 'milestones' => 'static_pages#milestones'
  resources :users do
    resources :statements
    
  end 
  resources :monsters
  get 'all_users' => 'users#index'
  get 'signup' => 'users#new'
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :characters
  get 'character_creator' => 'characters#new'
  put 'action' => 'characters#character_action'

  resources :games do
    resources :statements
    resources :encounters 
  end

  resources :combat_actions

  get 'play/:id' => 'games#play'
  get 'game_stuff' => 'static_pages#games'
  get 'choose_character' => 'games#pick_character'
  put 'add_to_game' => 'games#add_character_to_game'
  get 'games/:id/characters' => 'games#game_characters'
  get 'your_games' => 'games#games_you_play' 
  get 'games/:id/add_monsters' => 'games#add_monsters_to_games'

  post 'statements/do_action' => 'statements#do_action'
  post 'statements/make_saves' => 'statements#make_saves'
  post 'games/add_monsters' => 'games#save_monsters_to_games'
  post 'monsters/add_abilities' => 'monsters#save_abilities_to_monsters'
  post 'join_game_requests/send' => 'join_game_requests#send_request'
  post 'join_game_requests/answer' => 'join_game_requests#answer_request'
  

end

app/models/game.rb
class Game < ActiveRecord::Base
	has_many :characters
	has_many :statements
	has_many :encounters
	
	has_many :monster_ownerships
	has_many :monsters, :through => :monster_ownerships	

	has_many :item_ownerships
	has_many :weapons, :through => :item_ownerships
	has_many :armors, :through	=> :item_ownerships	
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	include CharactersHelper

	before_action :character_belongs_to_game, only: [:edit]
	before_action :logged_in_user, only: [:new, :edit, :show]
	def new
		@user = current_user
		@game = Game.new
	end

	def create
		@game = Game.new(params[:game])
		@game.gamemaster_id = current_user.id
		@game.body = "game initiated"
		@game.save
		redirect_to @game
	end

	def show
		@user = current_user
	 	@game = Game.find(params[:id])
	 	@master_id = @game.gamemaster_id 
	 	@is_playing_game = @game.characters.where(user_id: @user.id)
	 	@can_make_request = (JoinGameRequest.where(player_id: @user.id, game_id: params[:id])[0].nil?|| !@is_playing_game)
	 	@requests = JoinGameRequest.where(game_id: params[:id]) 
	 	@monsters = @user.monsters
	 	@current_monsters = @game.monsters
	 	@characters = @game.characters
	 	@encounters = @game.encounters
	end 

	def edit
		@user = User.find(current_user.id)
		@character = @user.characters.where(game_id: params[:id])[0]
		@game = Game.find(params[:id])
		@statement = @character.statements.new(game_id: params[:id])

	end
	
	def update		
		@break = "<p>#{params["game"]["statement"]} <p>"
		@user = User.find(current_user)
		@character = @user.characters.where(game_id: params[:id])[0]
		x = json_to_hash(my_character.strength)
		@game = Game.find(params[:id])
		@statement = @character.statements.new(game_id: params[:id])
		puts "hey #{params["game"]["statement"]}"
		if params["game"]["statement"] == "strength"
			#puts "here it is #{json_to_hash(my_character.strength)["mod"]}"
			@game.body = @game.body << "strength_mod: #{x}"
		else
			@game.body = @game.body << "#{@break}"
		end		
		@game.statement = nil
		@game.update_attributes(game_params)
		render 'edit'
	end

	def index
		@games = Game.all
	end

	def pick_character
		@game = Game.find(params[:game])
		@user = User.find(params[:guy])
		@characters = Character.where(user_id: params[:guy])
	end

	def add_character_to_game
		@user = User.find(params[:guy])
		@character = Character.find(params[:character])
		@character.update_attribute(:game_id, params[:game])
		params[:id] = params[:game]
		redirect_to "/games/#{params[:game]}/characters"
	end

	def game_characters
		@game = Game.find(params[:id])
		@characters = @game.characters

	end

	def games_you_play
		ids=[]; @guys = current_user.characters
		@guys.find_each do |guy|
			ids << guy.game_id
		end	
		@games_you_play = Game.where(id: ids)
		@your_games = Game.where(gamemaster_id: current_user.id)
	end

	def games_you_run
		@your_games = Game.where(gamemaster_id: current_user.id)
	end

	def add_monsters_to_games
		@game = Game.find(params[:id])
		@user = current_user
		@monsters = @user.monsters
	end

	def save_monsters_to_games
		@game = Game.find(params[:game_id])
		@user = current_user
		@monsters = @user.monsters
		targets = []
		#loop through @monsters,
		@monsters.each do |monster|
			#if a parameter with that monsters id exists associate it to @game
			if params["monster"+monster.id.to_s] == '1'
				@game.monsters << monster
			else
				puts "#{monster} doesn't seem to be selected"	
			end
		end 
		@game.save
		puts "#{@game.monsters} "
		#save @game
		redirect_to @game
	end
#################
    def game_params
      params.require(:game).permit(:body, :statement)
    end	

    def character_belongs_to_game
    	puts "hey hey #{params[:id]}"
    	@game_id = params[:id]
    	@user_id = current_user.id
    	@characters = Character.where(user_id: @user_id).where(game_id: params[:id])
    
    	
    	if @characters[0] == nil
    			flash[:danger] = "you can only edit games you belong to"
    			redirect_to root_url
    	end	
    end

    def logged_in_user
    	puts "here I am checking to see if you're logged in"
    	unless logged_in?
    		flash[:danger] = "please login to create a character"
    		redirect_to root_url
    	end		
	end

    def my_character
    	@game = Game.find(params[:id])
    	@character = @game.characters.where(user_id: current_user.id)[0]
    	return @character
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/add_monsters_to_games.html.erb
<%= form_tag("/games/add_monsters", method: "post") do %>
	<% @monsters.each do |monster| %>
		<%= label_tag("monster"+monster.id.to_s, monster.name) %>
		<%= check_box_tag("monster"+monster.id.to_s) %>
	<% end %>
	<%= submit_tag("add to your game") %>
	<%= hidden_field_tag(:game_id, @game.id) %>
<% end %>

app/views/games/edit.html.erb
<p> body: <%= @game.body %> </p>

<%= form_for @game do |f| %>

<p>
  <%= f.text_area :statement %>
</p>
<p>
  <%= f.submit %>
</p>

<% end %>

<%= form_for @statement do |f| %>
	
<p>
  <%= f.text_area :content %>
</p>
<p>
  <%= f.submit %>
</p>

<% end %>
 


<% x = "/action?character=#{@character.id}&amp;game=#{@game.id}&amp;guy=#{@user.id}"%>
<a data-method="put" href= <%= x %> > 
	<%= "act"%>
</a>  

app/views/games/game_characters.html.erb
<h1> I LIIIIVE!!!</h1>
<% @characters.each do |character| %>
	<%= link_to "#{character.race} #{character.character_class}", character %>
<% end %>

app/views/games/games_you_play.html.erb
<h2> games </h2>
<div id='sub-container'>
	<ul id='super-list'>
		<li id="your-games-menu">
		    games you run
		    <ul id="sub-things">
		      <li id="new"><%= link_to "start a new game", "/games/new" %></li>     
		      <% @your_games.each do |game| %>
				<% @owner = User.find(game.gamemaster_id) %>
		        <li>
					<%= link_to "#{ @owner.email}'s game", new_game_statement_path(game) %>
		        </li>
		      <% end %>
		    </ul>
	  </li>

	  <li id="games-you-play-menu">
		    games you're playing
		    <ul id="sub-things">
		      <li id="new"><%= link_to "request to join a game (not running yet)", games_path %></li>     
				<% @games_you_play.each do |game| %>
					<% @owner = User.find(game.gamemaster_id) %>
		        <li>
				<%= link_to "#{ @owner.email}'s game", new_game_statement_path(game) %>
		        </li>
		      <% end %>
		    </ul>
	  </li>
	</ul>
</div>

app/views/games/index.html.erb
<% @user = current_user %>
id: <%= @user.id %>
<ul id="games-index">
  <h1> choose a game to join </h1>
  <% @games.each do |game| %>
	<% if game.gamemaster_id != nil && game.gamemaster_id != current_user.id %>
		<% user = User.find(game.gamemaster_id) %>
    	<% my_character = current_user.characters.where(game_id: game.id) %>

		<% if  my_character[0].nil? %>
			<li>
	     	 <%= link_to "#{user.username}'s game", "/games/#{game.id}"%>       
	    	</li>
		<% else %>
			<% guy = my_character[0] %>
			<%= "you already joined #{user.email}'s
			 game with #{guy.race} #{guy.character_class}" %>
		<% end %>	    
	<% end %>

  <% end %>
</ul>

app/views/games/new.html.erb
<header id="game-form-title" >Just give your new game a name</header>

<div class="form-container">
	<%= form_for @game, :html => {:class => 'form'} do |f| %>
		<p>
 			<%= f.text_field(:name) %>
 		</p>
		<p id="submit-button">
		  <%= f.submit %>
		</p>
	<% end %>
</div>

app/views/games/pick_character.html.erb
<p> <%= @user.email %> plays <%= @game %> with:  </p>

<%= link_to "make a new character for this game", character_creator_path %>

<% @characters.each do |character| %>
	<% x = "/add_to_game?character=#{character.id}&amp;game=#{@game.id}&amp;guy=#{@user.id}"%>
	 

	 <li>
      <a data-method="put" href= <%= x %> > 
      	<%= "#{character.race} #{character.character_class}"%>
      </a>       
    </li>
<% end %>

app/views/games/show.html.erb
<div id='show-game-container'>
	<h2 id='title'> <%= @game.name %> </h2>

	<%= link_to "moop",  new_user_statement_path(:user_id => @user.id, :game_id => 8)%>

	<div id='show-game-characters'>
		<h3>characters playing this game</h3>
		<% @characters.each do |character| %>
			<p><%= link_to "#{character.name}", "/characters/#{character.id}" %></p> 
		<% end %>
	</div>

	<% if @user.id != @game.gamemaster_id  %>
		<% if !@user.characters.nil? %>		
			<% if @can_make_request %>
				<ul id="super-list">
					<li id="your-games-menu">
					    ask to join game
					    <ul id="sub-things">				         
					      <% @user.characters.each do |character| %>
					        <li>
								<%= link_to "with #{character.name}", controller: "join_game_requests", action: "send_request", player: @user.id, master: @master_id, character: character.id, game: params[:id], method: :post%>
					        </li>
					      <% end %>
					    </ul>
				  </li>
				</ul>			
			<% end %>
		<% end %>
	<% end %>
	<div id='show-game-monsters'>
		<h3>monsters included in this game</h3>
			<% @monsters.each do |monster| %>
				<p><%= link_to "#{monster.name}", "/monsters/#{monster.id}" %></p>
			<% end %>
	</div>
	
	<% if @user.id == @game.gamemaster_id  %>

		
		<div id='new-monster-form'>
			<h3>add monsters to this game</h3>
			<%= form_tag("/games/add_monsters", method: "post") do %>
				<% @monsters.each do |monster| %>
					<p><%= label_tag("monster"+monster.id.to_s, monster.name) %>
					<%= check_box_tag("monster"+monster.id.to_s) %>
					</p>		
				<% end %>
				<%= submit_tag("add to your game") %>
				<%= hidden_field_tag(:game_id, @game.id) %>
			<% end %>
		</div>
			
		<div id='requests'>
			<h3> requests to join </h3>
			<% @requests.each do |request| %>
				<% guy = Character.find(request.player_id) %>

				<%= link_to "#{guy.name}", "/characters/#{guy.id}" %>
				<%= link_to "accept", controller: "join_game_requests", action: "answer_request", request_id: request.id, player: request.player_id, master: request.master_id, character: request.character_id, answer: true, game: params[:id], method: :post%>
				<%= link_to "decline", controller: "join_game_requests", action: "answer_request", request_id: request.id, player: request.player_id, master: request.master_id, character: request.character_id, answer: false, game: params[:id], method: :post%>		
			<% end %>
		</div>	
	<% end %>

</div>