config/routes.rb
Rails.application.routes.draw do
  get 'join_game_requests/send_request'

  get 'join_game_requests/answer_request'

  root 'static_pages#home'
  get 'milestones' => 'static_pages#milestones'
  resources :users do
    resources :statements
    
  end 
  resources :monsters
  get 'all_users' => 'users#index'
  get 'signup' => 'users#new'
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :characters
  get 'character_creator' => 'characters#new'
  put 'action' => 'characters#character_action'

  resources :games do
    resources :statements
    resources :encounters 
  end

  resources :combat_actions

  get 'play/:id' => 'games#play'
  get 'game_stuff' => 'static_pages#games'
  get 'choose_character' => 'games#pick_character'
  put 'add_to_game' => 'games#add_character_to_game'
  get 'games/:id/characters' => 'games#game_characters'
  get 'your_games' => 'games#games_you_play' 
  get 'games/:id/add_monsters' => 'games#add_monsters_to_games'

  post 'statements/do_action' => 'statements#do_action'
  post 'statements/make_saves' => 'statements#make_saves'
  post 'games/add_monsters' => 'games#save_monsters_to_games'
  post 'monsters/add_abilities' => 'monsters#save_abilities_to_monsters'
  post 'join_game_requests/send' => 'join_game_requests#send_request'
  post 'join_game_requests/answer' => 'join_game_requests#answer_request'
  

end

app/views/layouts/_footer.html.erb
<div id="footer">
 
	<%= link_to "milestones page", '/milestones', class: "thing" %> |

	<%= link_to "guildHouse on gitHub", 'https://github.com/kjsuarez/guildHouse' %> |

	<%= link_to "bug report", 'https://github.com/kjsuarez/guildHouse/issues' %> |

	<%= link_to "about the developer", 'http://kjsuarez.github.io/' %> 

</div>
<div id="footer-background"></div>

app/views/layouts/_header.html.erb
<% unless current_user.nil? %>
	<% ids=[]; @guys = current_user.characters %>
	<% @guys.find_each do |guy| %>
		<% ids << guy.game_id %>
	<% end %>
	<% @games = Game.where(id: ids) %>
	<% @your_games = Game.where(gamemaster_id: current_user.id)%>
<% end %>


<div class="header">
	<ul >
		<li> <%= link_to "home",root_path, id: "tab"%> </li>
		<% if logged_in? # method deffined in sessions_helper %>
			<li> <%= link_to "profile", user_path(current_user), id: "tab" %>	 </li>
			<li> <%= link_to "characters", "/characters", id: "tab" %> </li>
			<li> <%= link_to "games", your_games_path, id: "tab" %> </li>
			<li><%= link_to "Log out", logout_path, method: "delete", id: "tab" %> </li>
		<% else %>
			<li> <%= link_to "sign up",signup_path, id: "tab" %> </li>
			<li> <%= link_to "login",login_path, id: "tab" %> </li>
		<% end %>
	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GuildHouse</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div class="container">   
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %> 
  <div id="content">
    <%= yield %>
  </div>       
    
     <%= render 'layouts/footer' %>
  </div>
 
</body>
</html>